


<?php 

$form = $this->loginForm;
$form->prepare();
echo $this->form()->openTag($form);
?>
<p>
<table class="login">
  <tr>
    <td> <?php echo ('邮箱&nbsp&nbsp') . $this->formElement($form->get('email')); ?>
    </td>
  </tr>
  <tr>
    <td>  <?php echo ("密码&nbsp&nbsp") . $this->formElement($form->get('pwd')); ?>
        <span class="common-error-msg"><?php  
             if ($this->error != NULL){
                echo "<ul><li>" . $this->error . "</li></ul>";
            }else{
                echo $this->formElementErrors($form->get('pwd'));
            }         
        ?></span>
    </td>
  </tr>
  <tr>
    <td>
    <?php
        echo $this->formRow($form->get('loginCsrf'));
        echo $this->formElement($form->get('submit'));
    ?>
    </td>
  </tr>
</table>
    <div>
            <span class="common-error-msg-d"><?php //echo $this->formElementErrors($form->get('email'));?></span>
    </div>
<?php echo $this->form()->closeTag($form)?>
