
<div class="col-xs-7 main-content">
    <div id="content">
        <div class="content-page news-content-wrapper">	
    		<div class="news-detail">
    			<h1 class="news-title">会员介绍</h1>
    			<div class="news-content">
    				<p>四通会员是四通为客户建立的长期回馈体系，从您成为四通会员的这一刻开始，您就在顺丰拥有了专属个人账户、尊贵的会员特权，我们竭尽全力，让您享受更优质的服务。</p>
                    <p><span class="enhance-text"><strong>轻松3步注册会员</strong></span></p>
                    <p>&nbsp;&nbsp;&nbsp; <a href="login/inscrit" target="_blank">立即注册</a></p>
                    <p><img style="width: 501px; display: block; margin-left: auto; margin-right: auto;" title="注册会员" src="/images/sfexpress/RegMember.jpg" alt=""></p>
                    <p>&nbsp;</p>
    			</div>
    		</div>
    	</div>
    </div>
</div>