<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('四通速递')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/express.css')
                        ->prependStylesheet($this->basepath() . '/css/jquery.dataTables.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basepath() . '/css/main.css?v=2015-07-04_12')?>


        
        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basepath() . '/js/jquery.dataTables.min.js')
                                      ->prependFile($this->basepath() . '/js/express.js')
                                      ->prependFile($this->basepath() . '/js/modernizr.js')
                                      ->prependFile($this->basepath() . '/js/express.js')
                                      ->prependFile($this->basepath() . '/js/jquery-ui-1.11.4/jquery-ui.min.js')
                                      //->prependFile($this->basePath() . '/js/jquery.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery-ui-1.11.4/external/jquery/jquery1.11.js')
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')

        ?>
                                      
       <script type="text/javascript" charset="utf-8"  data-requirecontext="_" data-requiremodule="/js/main.js?v=2015-07-04_12" src="/js/main.js?v=2015-07-04_12"></script>
 
     <!--  <script type="text/javascript" src="/js/express.js" ></script> -->
              
       
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta charset="utf-8">
  <meta name="renderer" content="webkit">
   
    

        
        
      <!--[if lt IE 8]>
    
    <div id ="old-ie-hint"> <p class='lt-ie8'>很抱歉，您使用的浏览器暂不支持，将为您的使用带来不便。请更换或升级为IE8以上、Chrome、Firefox、Safari进行浏览。<a href="#" onclick="javascript:$('p.lt-ie8').css('display','none'); ">取消</a></p> </div>
    <script language="JavaScript">
      (function() {
        var test = /access-type=(\d)/.exec(document.cookie);
        var accessType = test ? test[1] : null;
         if (accessType === "1") {
          document.getElementById("old-ie-hint").innerHTML = "很抱歉，您当前的浏览器版本过低，网站无法正常显示。 请点击<a href='http://10.0.11.111:8080/Chrome_V20_11.exe'>下载谷歌浏览器</a>，下载后点击“运行”自动安装。<br /> 如您的浏览器版本已经是IE8及以上，请关闭兼容模式视图：点击右上角“工具”->兼容性视图>在弹出窗口中取消勾选兼容性视图选项。<br />感谢您对顺丰速运的支持与关注！";
        }
      })();
    </script>
    
    <![endif]-->
      <meta name="description" content="">
      <meta name="keywords" content="">
      <meta name="viewport" content="width=device-width">
      <link rel="shortcut icon" href="/images/sfexpress/favicon.ico">

              
     
         
      <!-- build:js scripts/vendor/modernizr.js -->

      <!-- endbuild -->
    
      
      <script>
        (function() {
            var url=window.location.href;
            if(url.indexOf('direct')==-1&&(url.substr(url.length-'cn/sc/'.length,'cn/sc/'.length)=='cn/sc/'||
            url.substr(url.length-'cn/sc/index.html'.length,'cn/sc/index.html'.length)=='cn/sc/index.html')){
             var sUserAgent = navigator.userAgent.toLowerCase();
             var bIsIpad = sUserAgent.match(/ipad/i) == "ipad";
             var bIsIphoneOs = sUserAgent.match(/iphone os/i) == "iphone os";
             var bIsMidp = sUserAgent.match(/midp/i) == "midp";
             var bIsUc7 = sUserAgent.match(/rv:1.2.3.4/i) == "rv:1.2.3.4";
             var bIsUc = sUserAgent.match(/ucweb/i) == "ucweb";
             var bIsAndroid = sUserAgent.match(/android/i) == "android";
             var bIsCE = sUserAgent.match(/windows ce/i) == "windows ce";
             var bIsWM = sUserAgent.match(/windows mobile/i) == "windows mobile";
             var bIsIE = sUserAgent.match(/iemobile/i) == "iemobile";
             if (bIsIpad || bIsIphoneOs || bIsMidp || bIsUc7 || bIsUc || bIsAndroid || bIsCE || bIsWM||bIsIE) {
                //var current_uri='/cn/sc/index.html';
                //var current_folder='/cn/sc/';
                 if(url.indexOf('#search/bill-number')>-1){
                 window.location.href='../../mobile/cn/sc/dynamic_functions/waybill/waybill_query_by_billno.html';
                 }else if(url.indexOf('#search/phone-number')>-1){
                 window.location.href='../../mobile/cn/sc/dynamic_functions/waybill/waybill_query_by_mobilephone.html';
                 }else if(url.indexOf('waybill/cms_search.html')>-1){
                 window.location.href='../../mobile_1560643307';
                 }else{
                  window.location.href='../../mobile/cn/sc/index.html';
                 }
             }
         }
        })();
    </script>
    </head>
    
    <body class="language-sc">    
    <!--[if lt IE 9]>
    <script src="/js/json2.js"></script>
    <script src="/js/html5.js"></script>
    <script
        src="/js/respond.min.js"></script>
    <![endif]-->

    <header class="header">
        <div class="container">
            <ul class='logins'>            
                    <?php  
                        $session = new Zend\Session\Container("User");
                    
                        $nom = $session->offsetGet('nom');
                        $admin = $session->offsetGet('admin');

                        if ($nom != "")
                        {

                            echo "<li class='login'>" .  $nom . " ";
                            echo "</li>";
                            echo "<li class='login'>";
                            echo "<a href='/login/logout'>退出</a>";
                            echo "</li>";
                            echo "</ul>";
                        }else{
                            echo "<li class='login'>";
                            echo "<a href=\"login\">登录</a>";
                            echo "</li>";
                            echo "<li class=\"register\">";
                            echo "<a href=\"/login/add\">注册</a>";
                            echo "</li>";
                        }
                    
                    ?>
          </ul>
                  
          <div id="channel_link_list" >
        	<ul class="channels">
        		 <li>	
        					<a href="/">首页</a>
        		  </li>
       		 <li>
					<a href="/aboutme">关于四通</a>
       		  </li>
           </ul>
        </div>
            <a class='logo go-root' href='#'>
                <img src="/images/sfexpress/logoSC.png" />              
            </a>
          </div>
    </header>
    
    <div id="main_navgation">
        <nav class="navigation">
            <ul class="container">

                <li class='main-navigation-item first private'>
                    <!--第一个超级菜单加 first、private 这个类-->
                    <div class='main-navigation-title'>				           
                        <span><?php if(0 < $admin){echo "包裹管理";}else{echo "邮寄包裹";} ?></span>
                        <span class="connector"></span>	       
                    </div>
        					
                    <div class="mega-menu sending">
                        <div class="column first">
                            <div class="service-location-inputs location-inputs mini-inputs" data-redirect="true">                                                    
                                 <!-- <span class="sending-at-once go-dynamic"> -->
                                    <?php 
                                        if (0 < $admin){
                                            echo "<a href='/admin' target=''><img src='/images/sfexpress/order-button-icon.gif' />查看包裹清单</a>";
                                        }else{
                                            echo "<span class='sending-at-once go-dynamic'>";
                                            echo "<a href='/colis/add' target=''><img src='/images/sfexpress/order-button-icon.gif'>马上下单</a>";
                                            echo "</span>";
                                            echo "<a href='/colis' target=''>查看包裹清单2</a>";
                                        }                                        
                                    ?>
                                 <!--  </span>  -->                                
                            </div>
                        </div>
                    </div>
	            </li>
								
        								
        	   <li class="main-navigation-item private"> <!--前两个个超级菜单加 private 这个类-->		
        			<div class="main-navigation-title">
        				<span><?php if (0 < $admin) 
        				                echo "会员管理"; 
        				            echo "会员"; ?>
        				</span>
        				<span class="connector"></span>
        			</div>
        
                    <div class="mega-menu member">
                    	
                    	<div class="column first">
                			<?php 
                			if (0 == $admin){
                			     echo "<div class='how-to'>";
                				 echo   "<img src='/images/sfexpress/question.png'><a href='/login/introduction' target='_blank'>如何成为个人会员</a>";
                			     echo "</div>";
                			     
                			     echo "<div class='title'>个人会员</div>";
                			     
                			     echo "<div class='member-login-signup clearfix'>";
                			     echo    "<a class='member-login' href='/login' target='_blank'><img src='/images/sfexpress/login.png'>登录</a>";
                			     echo    "<a class='member-login' href='login/add' target='_blank'><img src='/images/sfexpress/signup.png'>注册</a>";
                			     echo "</div>";
                			}else{
                				echo "<div class='member-login-signup clearfix'>";
                                echo    "<a class='member-login' href='/login' target='_blank'><img src='/images/sfexpress/login.png'>查看所有会员</a>";
                                echo    "<a class='member-login' href='login/add' target='_blank'><img src='/images/sfexpress/signup.png'>会员充值</a>";
                                echo "</div>";
                			}
                			?>
                			
                    	</div>
                    </div> 				
        		</li>	

		</ul>
	</nav>
</div>




    
            <!-- // zend container  -->   
        <div class="">
            <?php echo $this->content; ?> 
        </div> <!-- /container -->
        
        
        
        <?php echo $this->inlineScript() ?>
    
    
    
    <footer class="footer">
        <div class="container">
            <div class="footer-links">
                <div id="footer_link_list"></div>
                <div class="record-number"></div>
                <div class="copy-right">© 2015 四通速运 版权所有</div>
            </div>
        </div>
    </footer>

            <!-- build:js scripts/main.js -->



<script data-main="/js/main.js?v=2015-08-09_12"
        src="/js/require.js"></script>
<script>
    require.config({
        waitSeconds: 0
    });
</script>
<!-- endbuild -->


    </body>
</html>
