<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'TestView\Module'                        => __DIR__ . '/Module.php',
    'TestView\Controller\SkeletonController' => __DIR__ . '/src/TestView/Controller/SkeletonController.php',
    'TestViewTest\Framework\TestCase'        => __DIR__ . '/tests/TestView/Framework/TestCase.php',
    'TestViewTest\SampleTest'                => __DIR__ . '/tests/TestView/SampleTest.php',
);
