

<div class="client-colis-title">
    <h1><?php echo $this->escapeHtml("客户包裹清单")?> </h1>
</div>  

<?php 
    use Zend\Form\Element;
    use Zend\Form\Form;

    $dateDebutElement = new Element\Text("colis-date-debut");
    $dateDebutElement->setAttribute('id', 'client-colis-date-debut');
    
    
    $dateFinElement = new Element\Text("colis-date-fin");
    $dateFinElement->setAttribute('id','client-colis-date-fin');
    
    
    $submitElement = new Element\Submit("submit");
    $submitElement->setValue("查询");
    
    $colisForm = new Form();
    $colisForm->add($submitElement);
    $colisForm->add($dateDebutElement);
    $colisForm->add($dateFinElement);
    $colisForm->prepare();      
?>
  
<div id="client-colis-search">

    <table id="client_colis_date_search">
        <tr>
            <th>开始时间</th>
            <th>结束时间</th>
            <th></th>
            <th></th>
            <th>余额</th>
            <th>押金</th>
           
        </tr>
    
        <tr>
             <?php echo $this->form()->openTag($colisForm); ?>
                <td> <?php echo $this->formElement($dateDebutElement); ?></td>
                <td><?php echo $this->formElement($dateFinElement); ?></td>
                <td><?php echo $this->formelement($submitElement); ?></td>
            <?php echo $this->form()->closeTag(); ?>
            <td></td>
          <!--    <td><?// php echo $this->escapehtml($this->assurance) ?></td>  -->
             <td><span 
             <?php 
                if (($this->solde - 100) < 100) 
                {
                    echo "class='client_solde_red'";
                }else{
                    echo "class='client_solde'";
                } 
             ?> ><?php echo $this->escapehtml($this->solde-100) ?></span></td>
             <td><?php echo $this->escapehtml(100) ?></td> 
        </tr>
    </table>
</div>
 
 <br>
 <br>
   
<table id='client-colis-list' class="display dataTable">
    <thead>
        <tr>
            <th class="details-control sorting_disabled"></th>
            <th>发件人</th>
            
            <th style="display:none">发件人地址</th>
            <th style="display:none">发件人邮编</th>
            <th style="display:none">发件人城市</th>
            <th style="display:none">发件人电话</th >            
            
            <th>包裹号</th>
            <th>收件人</th>
            <th style="display:none">收件人地址</th>
            <th style="display:none">收件人城市</th>
            <th style="display:none">收件人邮编</th>
            <th style="display:none">收件人电话</th>
            <th style="display:none">收件人国家</th>
            <th>包裹估重</th>
            <th>估算邮费</th>
            <th>保险金额</th>
            <th>下单时间</th>
            <th>实际重量</th>
            <th>实际邮费</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->allColis as $colis): ?>
        <tr>
            <td class="details-control"></td>
            <td><?php echo $this->escapeHtml($colis['expediteurNom']); ?></td>
            
            <td style="display:none"><?php echo $this->escapeHtml($colis['expediteurAdresse']); ?></td>
            <td style="display:none"><?php echo $this->escapeHtml($colis['expediteurVille']); ?></td>
            <td style="display:none"><?php echo $this->escapeHtml($colis['expediteurCodePostale']); ?></td>
            <td style="display:none"><?php echo $this->escapeHtml($colis['expediteurTelephone']); ?></td>
            
            <td><?php echo $this->escapeHtml($colis['refColis']); ?></td>
            <td><?php echo $this->escapeHtml($colis['destinateurNom']); ?></td>
            <td style="display:none"><?php echo $this->escapeHtml($colis['destinateurAdresse']); ?></td>
            <td style="display:none"><?php echo $this->escapeHtml($colis['destinateurVille']); ?></td>
            <td style="display:none"><?php echo $this->escapeHtml($colis['destinateurCodePostale']); ?></td>
            <td style="display:none"><?php echo $this->escapeHtml($colis['destinateurTelephone']); ?></td>
            <td style="display:none"><?php echo $this->escapeHtml($colis['destinateurPay']); ?></td>
            <td><?php echo $this->escapeHtml($colis['poidsPrevu']); ?></td>
            <td><?php echo $this->escapeHtml($colis['prixPrevu']); ?></td>
            <td><?php echo $this->escapehtml($colis['colisAssurance']); ?></td>
            <td><?php echo $this->escapeHtml($colis['depotTime']); ?></td>
            <td><?php echo $this->escapeHtml($colis['poidsFinal']); ?></td>
            <td><?php echo $this->escapeHtml($colis['prixFinal']); ?></td>
            <?php 
            if (empty($colis['refColis'])){
                echo "<td><a href='" . $this->url('colis', array('action'=>'index', 'id'=>$colis['id'])) . "'>出单</a></td>";
                echo "<td>凭证</td>";
            }else{ 
                echo "<td><a href='" . $colis['pdfUrl'] . "'>下载</a></td>";
                echo "<td><a href='/colis/telecharger/" . $colis['id'] . "'>凭证</a></td>";
               
            }
                
            ?>

       </tr>
       <?php endforeach;?>
       <tfoot>
       <tr> 
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>合计:</td>
            <td class='post_frais'></td>
            <td class='assurance_frais'></td>
            <td></td>
       </tr>
       </tfoot>
       
   </tbody>
 </table>

<?php 

    if ($this->flashMessenger()->hasMessages()) {
    
    	$messages = $this->flashMessenger()->getMessages();
    	foreach($messages as $message) {
    		if ($message == "notSolde")
    			echo"<script>alert('您的余额不足，请尽快充值');</script>";
    	}
    }

?>


