


<div class="content index-page">
	<div id="banner">

    <div class="banner">
		<a style="margin-left: -960px;  position: absolute;  left: 50%;  min-height: 472px;  vertical-align: middle;border:0;" href="/" target="_blank">
		<img src="/images/sfexpress/1030-0702-sc.jpg"></a>
    </div>


</div>
	<div class="container">
		<div class="row news-activities">
			<div class="col-xs-3 news-list">
				<h4 class="section-title">
				  <span class="section-title__text">新闻公告</span>
				  
				</h4>
				<div id="news_list">
    <ul>
      

                    <li>
                            ‘会员特惠•卢钧窑’促销活动中奖名单
                        <script type="text/javascript">
                        var filename ="news/Winner-Announcement-of-the-Member-Privileges-Lu-Jun-Kiln-Promotional-Activity/";
                        var id ="78634195-2127-11e5-b520-a0369f4fdae2";
                        if(document.getElementById(id)!=null){
                        	document.getElementById(id).setAttribute("href",filename.replace("/en/","/sc/")); 
                        }
                    </script>
                    </li>
                    
					
                    <li>
                            顺丰会员‘父亲节寄件赢豪礼’活动中奖名单
                        <script type="text/javascript">
                        var filename ="news/Winner-Announcement-about-the-Send-Shipment-on-Fathers-Day-Win-Great-Gift-Activity/";
                        var id ="3bd16c93-1630-11e5-b520-a0369f4fdae2";
                        if(document.getElementById(id)!=null){
                        	document.getElementById(id).setAttribute("href",filename.replace("/en/","/sc/")); 
                        }
                    </script>
                    </li>
                    
					
                
                    
                    
					
                    <li>

                            “献樱情，找顺丰”微信游戏大奖获奖信息公告（6月2日—6月7日）

                        <script type="text/javascript">
                        var filename ="news/Announcement-of-Winner-List-of-the-Cherry-Special-Delivery-WeChat-Game-Activity-June-2-June-7/";
                        var id ="386ba8dc-10b6-11e5-8f6a-a0369f4fdae2";
                        if(document.getElementById(id)!=null){
                        	document.getElementById(id).setAttribute("href",filename.replace("/en/","/sc/")); 
                        }
                    </script>
                    </li>
                    
					
                
                    
                    
					
                    <li>
                            父亲节，让爱一路顺丰 
                        <script type="text/javascript">
                        var filename ="news/Fathers-day-Delivering-Love-for-You/";
                        var id ="f4f31349-0bf2-11e5-8f6a-a0369f4fdae2";
                        if(document.getElementById(id)!=null){
                        	document.getElementById(id).setAttribute("href",filename.replace("/en/","/sc/")); 
                        }
                    </script>
                    </li>
                    
					
                
                    
                    
					
                    <li>
                            物流巨头5亿筑巢——有人的地方就有“丰巢” 
                        <script type="text/javascript">
                        var filename ="news/Magnate-of-logistics-spent-500-million-on-setting-up-the-hivebox-Where-there-is-people-there-is-hivebox/";
                        var id ="b7a66665-0b46-11e5-8f6a-a0369f4fdae2";
                        if(document.getElementById(id)!=null){
                        	document.getElementById(id).setAttribute("href",filename.replace("/en/","/sc/")); 
                        }
                    </script>
                    </li>
                    
					
                
                    
                    
					
                    <li>
                            六月有大事发生，不信你微信下单试一试
                        <script type="text/javascript">
                        var filename ="news/Big-Event-on-June-00001/";
                        var id ="50776ec5-0b7d-11e5-8f6a-a0369f4fdae2";
                        if(document.getElementById(id)!=null){
                        	document.getElementById(id).setAttribute("href",filename.replace("/en/","/sc/")); 
                        }
                    </script>
                    </li>
                    
					
                
                    
                    
					
                    <li>
                            “让爱一路顺丰”520表白日大奖获奖信息公告（5.11-5.20）
                        <script type="text/javascript">
                        var filename ="news/Winner-Announcement-for-520-Day-Day-of-expressing-love-Activity-of-the-SF-Delivering-Love-for-You-Promotional-Period-May-11-May-20/";
                        var id ="ab7daae1-0b5a-11e5-8f6a-a0369f4fdae2";
                        if(document.getElementById(id)!=null){
                        	document.getElementById(id).setAttribute("href",filename.replace("/en/","/sc/")); 
                        }
                    </script>
                    </li>
                    
					
                
                    
                    
					
                    <li>
                            关于顺丰华南地区七个城市异地即日产品恢复原价的通知
                        <script type="text/javascript">
                        var filename ="news/Announcement-about-Restoring-the-Original-Prices-for-SFs-Inter-city-Same-Day-Delivery-between-7-South-China-Cities/";
                        var id ="0efef9d7-05a2-11e5-b18d-a0369f4fdae2";
                        if(document.getElementById(id)!=null){
                        	document.getElementById(id).setAttribute("href",filename.replace("/en/","/sc/")); 
                        }
                    </script>
                    </li>
                    
					
                
                    
                    
					
                    <li>
                            关于2015年5月23日官网维护通知 
                        <script type="text/javascript">
                        var filename ="news/Server-Maintenance-on-23suprd-sup-May-2015-00006/";
                        var id ="07d771eb-0033-11e5-833b-60c5479253e4";
                        if(document.getElementById(id)!=null){
                        	document.getElementById(id).setAttribute("href",filename.replace("/en/","/sc/")); 
                        }
                    </script>
                    </li>
                    
					
                
                    
                    
					
                    <li>
                            “让爱一路顺丰”母亲节大奖获奖信息公告（5.5-5.10） 
                        <script type="text/javascript">
                        var filename ="news/Winner-Announcement-for-Mothers-Day-Activity-of-the-SF-Delivering-Love-for-You-May-5-May-10/";
                        var id ="fe700834-feb8-11e4-833b-60c5479253e4";
                        if(document.getElementById(id)!=null){
                        	document.getElementById(id).setAttribute("href",filename.replace("/en/","/sc/")); 
                        }
                    </script>
                    </li>
                    
					
                
                    
                    
					
                    <li>
                            全新顺丰领先服务：顺丰次晨10：30AM准时送达！
                        <script type="text/javascript">
                        var filename ="news/Brand-new-Leading-Service-Provided-by-S.F.-Express-SF-Next-Morning-Delivery-Timely-Delivery-before-1030AM-the-Next-Morning-00001/";
                        var id ="ede7413e-f528-11e4-808f-60c5479253e4";
                        if(document.getElementById(id)!=null){
                        	document.getElementById(id).setAttribute("href",filename.replace("/en/","/sc/")); 
                        }
                    </script>
                    </li>
                    
					
                
                    
                    
					
                    <li>
                            关于取消中国大陆所有客户重货出口至港澳台清关服务费的通知
                        <script type="text/javascript">
                        var filename ="news/Announcement-about-Waiving-Service-Fee-of-Heavy-Cargoes-Exported-from-Mainland-China-to-Hong-Kong-Macau-and-Taiwan/";
                        var id ="9104c622-ef0d-11e4-a6c2-60c5479253e4";
                        if(document.getElementById(id)!=null){
                        	document.getElementById(id).setAttribute("href",filename.replace("/en/","/sc/")); 
                        }
                    </script>
                    </li>
                    
					
                
                    
                    
					
                    <li>
                            生鲜速配——岛城“莓”景，尽在顺丰 
                        <script type="text/javascript">
                        var filename ="news/Fresh-Product-Delivery-Qingdaos-Fresh-Blueberries-All-at-SF/";
                        var id ="887ee034-eca6-11e4-86a4-60c5479253e4";
                        if(document.getElementById(id)!=null){
                        	document.getElementById(id).setAttribute("href",filename.replace("/en/","/sc/")); 
                        }
                    </script>
                    </li>
                    
					
                
                    
                    
					
                    <li>

                            顺丰速运有限公司——公路运输项目采购招标公告

                        <script type="text/javascript">
                        var filename ="news/S.F.-Express-Co.-Ltd.-Road-Transportation-Project-Procurement-Tender-Announcement-00001/";
                        var id ="34ce45ad-e35b-11e4-b6f8-60c5479253e4";
                        if(document.getElementById(id)!=null){
                        	document.getElementById(id).setAttribute("href",filename.replace("/en/","/sc/")); 
                        }
                    </script>
                    </li>
                    
					
                
                    
                    
					
                    <li>

                            生鲜速配——献樱情，找顺丰

                        <script type="text/javascript">
                        var filename ="news/Fresh-Product-Delivery-Service-Cherry-Special-Delivery-Service/";
                        var id ="1bfe8f54-d823-11e4-b6f8-60c5479253e4";
                        if(document.getElementById(id)!=null){
                        	document.getElementById(id).setAttribute("href",filename.replace("/en/","/sc/")); 
                        }
                    </script>
                    </li>
                    
					
                
                    
                    
					
                    <li>
                        
                            顺丰22周年庆抢1000元现金红包
                        
                        <script type="text/javascript">
                        var filename ="news/RMB-1000-Lucky-Money-up-for-Grab-to-Celebrate-SFs-22nd-Anniversary/";
                        var id ="0243e25a-d2c9-11e4-b36f-60c5479253e4";
                        if(document.getElementById(id)!=null){
                        	document.getElementById(id).setAttribute("href",filename.replace("/en/","/sc/")); 
                        }
                    </script>
                    </li>
                    
					
                
            
        
    </ul>



		
		
	

</div>
			
			</div>
			
				<div class="col-xs-9">
					<div class="activities-promotion">
						<h4 class="section-title">
						  <span class="section-title__text">活动促销</span>
	
						</h4>
						<div id="promotion_list">




	
		<div class="activities-promotion promotion-list">
			<script>
				window.promotionActiveTime = [];
				window.promotionRegion = [];
			</script>

			<ul>
				
					
						
						<li>
							
							
							
							
							
						<a id="寄水蜜桃， iPhone 6抽奖送！ " href="promotion/Deliver-Honey-Peaches-with-SF-Win-iPhone-6-00001/" target="_blank" class="go-dynamic" data-with-return-page="true">
									<script type="text/javascript">
                    var filename ="promotion/Deliver-Honey-Peaches-with-SF-Win-iPhone-6-00001/";
                    var id ="寄水蜜桃， iPhone 6抽奖送！ ";
					if(document.getElementById(id)!=null){
                    document.getElementById(id).setAttribute("href",filename.replace("/en/","/sc/"));
					}
                    </script>
							
								
									<img src="/images/sfexpress/shuimitao2_small_sc.jpg">
								
								<div class="activity-content">

									<h5 class="promotion-title">寄水蜜桃， iPhone 6抽奖送！ </h5>
									<div class="description"></div>

									<div class="promotion_status_label hot_in" style="">进行中</div>
									<div class="promotion_status_label finished" style="display:none;">已结束</div>

									<div class="date">
										
                                            
                                            
                                            2015.7.1
                                                -
                                                2015.7.31
                                            
                                        
									</div>

									<div class="range">
						 			 
									
									
									华东-泰州市、无锡市、常州市、扬州市、镇江市、宁波市、舟山市、嘉兴市、湖州市、苏州市
									 适用
									
									
									</div>

									<script>
										window.promotionActiveTime.push({
											begin: 1435715040000,
											end: 1438358340000
										});
									</script>
								</div>
							</a>
						</li>
					
				
					
						
						<li>
							
							
							
							
									<a href="http://www.sfbest.com/html/activity/1435282557.html" target="_blank">
							
							
								
									<img src="/images/sfexpress/chihuo_small_sc.jpg">
								
								<div class="activity-content">

									<h5 class="promotion-title">吃货节，舌尖美食惠 </h5>
									<div class="description"></div>

									<div class="promotion_status_label hot_in" style="">进行中</div>
									<div class="promotion_status_label finished" style="display:none;">已结束</div>

									<div class="date">
										
                                            
                                            
                                            2015.6.30
                                                -
                                                2015.7.13
                                            
                                        
									</div>

									<div class="range">
						 			 
									
									
									中国大陆
									 适用
									
									
									</div>

									<script>
										window.promotionActiveTime.push({
											begin: 1435632854265,
											end: 1436803140000
										});
									</script>
								</div>
							</a>
						</li>
					
				
					
						
						<li>
							
							
							
							
									<a href="https://www.sfbuy.com/recruit" target="_blank">
							
							
								
									<img src="/images/sfexpress/japan_small_sc.jpg">
								
								<div class="activity-content">

									<h5 class="promotion-title">日淘免运费招募中 </h5>
									<div class="description"></div>

									<div class="promotion_status_label hot_in" style="">进行中</div>
									<div class="promotion_status_label finished" style="display:none;">已结束</div>

									<div class="date">
										
                                            
                                            
                                            2015.6.29
                                                -
                                                2015.7.6
                                            
                                        
									</div>

									<div class="range">
						 			 
									
									
									中国大陆
									 适用
									
									
									</div>

									<script>
										window.promotionActiveTime.push({
											begin: 1435561667493,
											end: 1436198340000
										});
									</script>
								</div>
							</a>
						</li>
					
				
			</ul>
		</div>
	

</div>
					</div>
					
					<div class="home-carousel">
						<h4 class="section-title">
		          <span class="section-title__text">
		            
		              个性推广信息
		          	
		          </span>
		        </h4>
						<div id="carousel-example-generic" class="carousel fade-in-out" data-ride="carousel">
							<div class="carousel-inner">					
										<div class="item">
											<a id="express/product_service/international/Russia_delivery/#pro" class="member-login" href="express/product_service/international/Russia_delivery/#" target="_blank">
												
													<img src="/images/sfexpress/russia_pro_sc.jpg">
												
											</a>
											<script type="text/javascript">
                                                var filename ="express/product_service/international/Russia_delivery/#";
                                                var id ="express/product_service/international/Russia_delivery/#pro";
    											if(document.getElementById(id)!=null){
    											    document.getElementById(id).setAttribute("href",filename.replace("/en/","/sc/"));
    											}
                                            </script>
										</div>
									
										<div class="item">
											<a id="https://www.sfbuy.com/recruitpro" class="member-login" href="https://www.sfbuy.com/recruit" target="_blank">
												
													<img src="/images/sfexpress/japan_pro_sc.jpg">
												
											</a>
											<script type="text/javascript">
                                            var filename ="https://www.sfbuy.com/recruit";
                                            var id ="https://www.sfbuy.com/recruitpro";
											if(document.getElementById(id)!=null){
                                            document.getElementById(id).setAttribute("href",filename.replace("/en/","/sc/"));
											}
                                            </script>
										</div>
											
										<div class="item">
											<a id="express/sf_cold_chain/pharma_ease/cold_chain_main_line_transportation/pro" class="member-login" href="express/sf_cold_chain/pharma_ease/cold_chain_main_line_transportation/" target="_blank">
												
													<img src="/images/sfexpress/95338-8-1-pro-sc.jpg">
												
											</a>
											<script type="text/javascript">
                                            var filename ="express/sf_cold_chain/pharma_ease/cold_chain_main_line_transportation/";
                                            var id ="express/sf_cold_chain/pharma_ease/cold_chain_main_line_transportation/pro";
											if(document.getElementById(id)!=null){
                                            document.getElementById(id).setAttribute("href",filename.replace("/en/","/sc/"));
											}
                                            </script>
										</div>
											
										<div class="item  active">
											<a id="express/sf_cold_chain/food_ease/cold_chain_home_delivery/pro" class="member-login" href="express/sf_cold_chain/food_ease/cold_chain_home_delivery/" target="_blank">
												
													<img src="/images/sfexpress/713-260px-0607.jpg">
												
											</a>
											<script type="text/javascript">
                                            var filename ="express/sf_cold_chain/food_ease/cold_chain_home_delivery/";
                                            var id ="express/sf_cold_chain/food_ease/cold_chain_home_delivery/pro";
											if(document.getElementById(id)!=null){
                                            document.getElementById(id).setAttribute("href",filename.replace("/en/","/sc/"));
											}
                                            </script>
										</div>
											
										<div class="item">
											<a id="news/Magnate-of-logistics-spent-500-million-on-setting-up-the-hivebox-Where-there-is-people-there-is-hivebox-00001/pro" class="member-login" href="news/Magnate-of-logistics-spent-500-million-on-setting-up-the-hivebox-Where-there-is-people-there-is-hivebox-00001/" target="_blank">
												
													<img src="/images/sfexpress/fengchao2_pro_sc.jpg">
												
											</a>
											<script type="text/javascript">
                                            var filename ="news/Magnate-of-logistics-spent-500-million-on-setting-up-the-hivebox-Where-there-is-people-there-is-hivebox-00001/";
                                            var id ="news/Magnate-of-logistics-spent-500-million-on-setting-up-the-hivebox-Where-there-is-people-there-is-hivebox-00001/pro";
											if(document.getElementById(id)!=null){
                                            document.getElementById(id).setAttribute("href",filename.replace("/en/","/sc/"));
											}
                                            </script>
										</div>
									
							</div>
							<ol class="carousel-indicators">
								<li data-target="#carousel-example-generic" data-slide-to="0" class=""></li><li data-target="#carousel-example-generic" data-slide-to="1" class=""></li><li data-target="#carousel-example-generic" data-slide-to="2" class=""></li><li data-target="#carousel-example-generic" data-slide-to="3" class=""></li><li data-target="#carousel-example-generic" data-slide-to="4" class="active"></li>
							</ol>
						</div>
					</div>
				</div>
			
		</div>
	</div>
</div>



<?php 
 //   $title = 'Test User';
 //   $this->headtitle($title, null);

?>
 
 <?php
 /*   commmendaire  test
<div class="header">
<h1>Welcome to front page</h1>
<table class="table">
    <tr>
        <th>nom</th>
        <th>prenom</th>
        <th>telephone</th>
    </tr>
  
    <?php foreach ($users as $user) :?>
    <tr>
        <td><?php echo $this->escapehtml($user->nom);?></td>
        <td><?php echo $this->escapehtml($user->prenom);?></td>
        <td><?php echo $this->escapehtml($user->telephone);?></td>
    </tr>
    <?php endforeach;?>
</table>
</div>
*/
?>