<?php 
use \Zend\Form\Element;
use \Zend\Form\Form;


$buttonElement = new Element\Submit("add-ads");
$buttonElement->setValue("添加新地址");
$newNom = new Element\Text('destinateur_nom');
$newAds = new Element\textarea('destinateur_ads');
$newVille = new Element\Text('destinateur_ville');
$newZip = new Element\Text('destinateur_zip');
$newTelephone = new Element\Text('destinateur_telephone');
$newPays = new Element\Select("destinateur_pays");
$newPays->setAttribute('id', "destinateur_pays");
$newPays->setAttributes(array(
		'AutoComplete' => true,
		'required' => true
));
$newPays->setValueOptions(array(
		"Chine"=>"Chine","Afghanistan"=>"Afghanistan",
		"Afrique_Centrale"=>"Afrique_Centrale","Afrique_du_sud"=>"Afrique_du_Sud",
		"Albanie"=>"Albanie","Algerie"=>"Algerie","Allemagne"=>"Allemagne",
		"Andorre"=>"Andorre","Angola"=>"Angola","Anguilla"=>"Anguilla",
		"Arabie_Saoudite"=>"Arabie_Saoudite","Argentine"=>"Argentine","Armenie"=>"Armenie",
		"Australie"=>"Australie","Autriche"=>"Autriche","Azerbaidjan"=>"Azerbaidjan",
		"Bahamas"=>"Bahamas","Bangladesh"=>"Bangladesh","Barbade"=>"Barbade",
		"Bahrein"=>"Bahrein","Belgique"=>"Belgique","Belize"=>"Belize","Benin"=>"Benin",
		"Bermudes"=>"Bermudes","Bielorussie"=>"Bielorussie","Bolivie"=>"Bolivie",
		"Botswana"=>"Botswana","Bhoutan"=>"Bhoutan","Boznie_Herzegovine"=>"Boznie_Herzegovine",
		"Bresil"=>"Bresil","Brunei"=>"Brunei","Bulgarie"=>"Bulgarie","Burkina_Faso"=>"Burkina_Faso",
		"Burundi"=>"Burundi","Caiman"=>"Caiman","Cambodge"=>"Cambodge","Cameroun"=>"Cameroun",
		"Canada"=>"Canada","Canaries"=>"Canaries","Cap_vert"=>"Cap_Vert","Chili"=>"Chili",
		"Chine"=>"Chine" ,"Chypre"=>"Chypre" ,"Colombie"=>"Colombie","Comores"=>"Colombie",
		"Congo"=>"Congo","Congo_democratique"=>"Congo_democratique","Cook"=>"Cook",
		"Coree_du_Nord"=>"Coree_du_Nord","Coree_du_Sud"=>"Coree_du_Sud","Costa_Rica"=>"Costa_Rica",
		"Cote_d_Ivoire"=>"Côte_d_Ivoire","Croatie"=>"Croatie","Cuba"=>"Cuba","Danemark"=>"Danemark",
		"Djibouti"=>"Djibouti","Dominique"=>"Dominique","Egypte"=>"Egypte",
		"Emirats_Arabes_Unis"=>"Emirats_Arabes_Unis","Equateur"=>"Equateur","Erythree"=>"Erythree",
		"Espagne"=>"Espagne","Estonie"=>"Estonie","Etats_Unis"=>"Etats_Unis","Ethiopie"=>"Ethiopie",
		"Falkland"=>"Falkland","Feroe"=>"Feroe","Fidji"=>"Fidji","Finlande"=>"Finlande",
		"France"=>"France","Gabon"=>"Gabon","Gambie"=>"Gambie","Georgie"=>"Georgie",
		"Ghana"=>"Ghana","Gibraltar"=>"Gibraltar","Grece"=>"Grece","Grenade"=>"Grenade",
		"Groenland"=>"Groenland","Guadeloupe"=>"Guadeloupe","Guam"=>"Guam","Guatemala"=>"Guatemala",
		"Guernesey"=>"Guernesey","Guinee"=>"Guinee","Guinee_Bissau"=>"Guinee_Bissau",
		"Guinee equatoriale"=>"Guinee_Equatoriale","Guyana"=>"Guyana","Guyane_Francaise "=>"Guyane_Francaise",
		"Haiti"=>"Haiti","Hawaii"=>"Hawaii" ,"Honduras"=>"Honduras","Hong_Kong"=>"Hong_Kong",
		"Hongrie"=>"Hongrie","Inde"=>"Inde","Indonesie"=>"Indonesie","Iran"=>"Iran","Iraq"=>"Iraq",
		"Irlande"=>"Irlande","Islande"=>"Islande","Israel"=>"Israel","Italie"=>"italie","Jamaique"=>"Jamaique",
		"Jan Mayen"=>"Jan Mayen","Japon"=>"Japon","Jersey"=>"Jersey","Jordanie"=>"Jordanie",
		"Kazakhstan"=>"Kazakhstan","Kenya"=>"Kenya","Kirghizstan"=>"Kirghizistan","Kiribati"=>"Kiribati",
		"Koweit"=>"Koweit","Laos"=>"Laos","Lesotho"=>"Lesotho","Lettonie"=>"Lettonie","Liban"=>"Liban",
		"Liberia"=>"Liberia","Liechtenstein"=>"Liechtenstein","Lituanie"=>"Lituanie" ,"Luxembourg"=>"Luxembourg",
		"Lybie"=>"Lybie","Macao"=>"Macao","Macedoine"=>"Macedoine","Madagascar"=>"Madagascar","Madère"=>"Madère",
		"Malaisie"=>"Malaisie","Malawi"=>"Malawi","Maldives"=>"Maldives","Mali"=>"Mali","Malte"=>"Malte","Man"=>"Man",
		"Mariannes du Nord"=>"Mariannes du Nord","Maroc"=>"Maroc","Marshall"=>"Marshall","Martinique"=>"Martinique",
		"Maurice"=>"Maurice","Mauritanie"=>"Mauritanie","Mayotte"=>"Mayotte","Mexique"=>"Mexique","Micronesie"=>"Micronesie",
		"Midway"=>"Midway","Moldavie"=>"Moldavie","Monaco"=>"Monaco","Mongolie"=>"Mongolie","Montserrat"=>"Montserrat",
		"Mozambique"=>"Mozambique","Namibie"=>"Namibie","Nauru"=>"Nauru","Nepal"=>"Nepal","Nicaragua"=>"Nicaragua",
		"Niger"=>"Niger","Nigeria"=>"Nigeria","Niue"=>"Niue","Norfolk"=>"Norfolk","Norvege"=>"Norvege",
		"Nouvelle_Caledonie"=>"Nouvelle_Caledonie","Nouvelle_Zelande"=>"Nouvelle_Zelande","Oman"=>"Oman",
		"Ouganda"=>"Ouganda","Ouzbekistan"=>"Ouzbekistan","Pakistan"=>"Pakistan","Palau"=>"Palau","Palestine"=>"Palestine",
		"Panama"=>"Panama","Papouasie_Nouvelle_Guinee"=>"Papouasie_Nouvelle_Guinee","Paraguay"=>"Paraguay",
		"Pays_Bas"=>"Pays_Bas","Perou"=>"Perou","Philippines"=>"Philippines" ,"Pologne"=>"Pologne","Polynesie"=>"Polynesie",
		"Porto_Rico"=>"Porto_Rico","Portugal"=>"Portugal","Qatar"=>"Qatar","Republique_Dominicaine"=>"Republique_Dominicaine",
		"Republique_Tcheque"=>"Republique_Tcheque","Reunion"=>"Reunion","Roumanie"=>"Roumanie","Royaume_Uni"=>"Royaume_Uni",
		"Russie"=>"Russie","Rwanda"=>"Rwanda","Sahara Occidental"=>"Sahara Occidental","Sainte_Lucie"=>"Sainte_Lucie",
		"Saint_Marin"=>"Saint_Marin","Salomon"=>"Salomon","Salvador"=>"Salvador","Samoa_Occidentales"=>"Samoa_Occidentales</option=>",
		"Samoa_Americaine"=>"Samoa_Americaine","Sao_Tome_et_Principe"=>"Sao_Tome_et_Principe" ,"Senegal"=>"Senegal",
		"Seychelles"=>"Seychelles","Sierra Leone"=>"Sierra Leone","Singapour"=>"Singapour","Slovaquie"=>"Slovaquie",
		"Slovenie"=>"Slovenie</option=>","Somalie"=>"Somalie","Soudan"=>"Soudan" ,"Sri_Lanka"=>"Sri_Lanka" ,"Suede"=>"Suede",
		"Suisse"=>"Suisse","Surinam"=>"Surinam","Swaziland"=>"Swaziland","Syrie"=>"Syrie","Tadjikistan"=>"Tadjikistan",
		"Taiwan"=>"Taiwan","Tonga"=>"Tonga","Tanzanie"=>"Tanzanie","Tchad"=>"Tchad","Thailande"=>"Thailande","Tibet"=>"Tibet",
		"Timor_Oriental"=>"Timor_Oriental","Togo"=>"Togo" ,"Trinite_et_Tobago"=>"Trinite_et_Tobago",
		"Tristan da cunha"=>"Tristan de cuncha","Tunisie"=>"Tunisie","Turkmenistan"=>"Turmenistan" ,"Turquie"=>"Turquie",
		"Ukraine"=>"Ukraine","Uruguay"=>"Uruguay","Vanuatu"=>"Vanuatu","Vatican"=>"Vatican","Venezuela"=>"Venezuela",
		"Vierges_Americaines"=>"Vierges_Americaines","Vierges_Britanniques"=>"Vierges_Britanniques","Vietnam"=>"Vietnam",
		"Wake"=>"Wake","Wallis et Futuma"=>"Wallis et Futuma","Yemen"=>"Yemen","Yougoslavie"=>"Yougoslavie","Zambie"=>"Zambie",
		"Zimbabwe"=>"Zimbabwe",
));



$adsForm = new Form();
$adsForm->setAttribute('action', $this->url('login/listads', array()), true);

$adsForm->add($buttonElement);
$adsForm->add($newNom);
$adsForm->add($newAds);
$adsForm->add($newTelephone);
$adsForm->add($newVille);
$adsForm->add($newZip);


$adsForm->prepare();


?>
<p>
<?php 
if ($this->message != '')
{
	echo "<h3>" . $this->message . "</h3>";
    
}


?>

<table id='list_ads' class='list_ads'>
    <thead>
        <tr>
            <td style="display: none;"></td>
            <td>收件人姓名</td>
            <td>收件人地址</td>
            <td>收件人邮编</td>
            <td>收件人城市</td>
            <td>收件人国家</td>
            <td>收件人电话</td>
            <td></td>
        </tr>
    </thead>
    <?php 
       foreach($this->allAds as $ads){    
            echo "<tr>";
            echo "<td style='display: none;'>" . $ads['id'] . "</td>";
            echo "<td>" . $ads['nom'] . "</td>";
            echo "<td>" . $ads['adresse'] . "</td>";
            echo "<td>" . $ads['codePostale'] . "</td>";
            echo "<td>" . $ads['ville'] . "</td>";
            echo "<td>" . $ads['pays'] . "</td>";
            echo "<td>" . $ads['telephone'] . "</td>";
            echo "<td> <a href='deleteads/" . $ads['id'] . "'>删除 </a></td>";
            echo "</tr>";
        }
    ?>
</table>

<p>
<?php echo $this->form()->openTag($adsForm);?>
<table id='add_ads' class='ads_ads'>
        <tr>
            <td>收件人姓名</td>
            <td><?php echo $this->formElement($newNom); ?></td>
        </tr>
         <tr>
            <td>收件人地址</td>
            <td><?php echo $this->formElement($newAds); ?></td>
         </tr>
         <tr>
            <td>收件人邮编</td>
            <td><?php echo $this->formElement($newZip); ?></td>
         </tr>
         <tr>
            <td>收件人城市</td>   
            <td><?php echo $this->formElement($newVille); ?></td>      
         </tr>
         <tr>
             <td>收件人国家</td>   
              <td><?php echo $this->formElement($newPays); ?></td>
         </tr>
         <tr>
             <td>收件人电话</td>
             <td><?php echo $this->formElement($newTelephone); ?></td>  
         </tr>
         <tr>
            <td colspan="2"><?php echo $this->formElement($buttonElement); ?></td>
         </tr>
</table>
<?php echo $this->form()->closeTag(); ?>


