<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Colis\Module'                        => __DIR__ . '/Module.php',
    'Colis\Controller\SkeletonController' => __DIR__ . '/src/Colis/Controller/SkeletonController.php',
    'ColisTest\Framework\TestCase'        => __DIR__ . '/tests/Colis/Framework/TestCase.php',
    'ColisTest\SampleTest'                => __DIR__ . '/tests/Colis/SampleTest.php',
);
