


<div class="content index-page">
	<div id="banner">

    <div class="banner">
		<a style="margin-left: -960px;  position: absolute;  left: 50%;  min-height: 472px;  vertical-align: middle;border:0;" href="/" target="_blank">
		<img src="/images/sfexpress/1030-0702-sc.jpg"></a>
    </div>


</div>
	<div class="container">
		<div class="row news-activities">
			<div class="col-xs-3 news-list">
    			<h4 class="section-title">			
    			<span class="section-title__text"></span>
    			  
    			</h4>
    			<div id="news_list">
                    <ul>
                    </ul>                
                </div>
			
			</div>
			
			<div class="col-xs-9">
				<div class="activities-promotion">
					<h4 class="section-title">
					  <span class="section-title__text">活动促销</span>

					</h4>
					<div id="promotion_list">




	
		<div class="activities-promotion promotion-list">
			<script>
				window.promotionActiveTime = [];
				window.promotionRegion = [];
			</script>

			<ul>	
			     <li>				
						<!--  <a id="iphone" href="" target="_blank" class="go-dynamic" data-with-return-page="true">  -->
						    <script type="text/javascript">
                                    //var filename ="promotion/";
                                    //var id ="iphone";
                					//if(document.getElementById(id)!=null){
                					//    document.getElementById(id).setAttribute("href",filename.replace("/en/","/sc/"));
                					//}
             				</script>
							
								
									<img src="/images/sfexpress/shuimitao2_small_sc.jpg">
								
								<div class="activity-content">
									<h5 class="promotion-title">会员回馈！送大礼！ </h5>
									<div class="description"></div>
									<div class="promotion_status_label hot_in" style="">进行中</div>
									<div class="promotion_status_label finished" style="display:none;">已结束</div>
									<div class="date">2015.7.15-2015.7.31</div>
									<div class="range"></div>
									<script>
										window.promotionActiveTime.push({
											begin: 1435715040000,
											end: 1438358340000
										});
									</script>
								</div>
						<!-- 	</a>   -->
						</li>
					
				
					
						
						<li>
<!-- 					  <a href="#" target="_blank">  -->
					       <img src="/images/sfexpress/chihuo_small_sc.jpg">
						      <div class="activity-content">
								<h5 class="promotion-title">奶粉促销，一站到底 </h5>
								<div class="description"></div>
								<div class="promotion_status_label hot_in" style="">进行中</div>
								<div class="promotion_status_label finished" style="display:none;">已结束</div>
								<div class="date">2015.7.30-2015.8.13</div>
								<div class="range">	</div>
								<script>
										window.promotionActiveTime.push({
											begin: 1435632854265,
											end: 1436803140000
										});
								</script>
							</div>
<!-- 						</a>  -->
						</li>
					
						<li>
<!--    			       	<a href="https://www.sfbuy.com/recruit" target="_blank"> -->
								<img src="/images/sfexpress/japan_small_sc.jpg">
								<div class="activity-content">
									<h5 class="promotion-title">精喜不断，下单就送!</h5>
									<div class="description"></div>
									<div class="promotion_status_label hot_in" style="">进行中</div>
									<div class="promotion_status_label finished" style="display:none;">已结束</div>
									<div class="date">2015.8.29-2015.9.6</div>
									<div class="range"></div>
									<script>
										window.promotionActiveTime.push({
											begin: 1435561667493,
											end: 1436198340000
										});
									</script>
								</div>
<!--  							</a>-->
						</li>
					
				
			</ul>
		</div>
</div>
					</div>
					
					<div class="home-carousel">
						<h4 class="section-title">
		          <span class="section-title__text">
		            
		              个性推广信息
		          	
		          </span>
		        </h4>
						<div id="carousel-example-generic" class="carousel fade-in-out" data-ride="carousel">
							<div class="carousel-inner">					
										<div class="item  active">			
											<img src="/images/sfexpress/713-260px-0607.jpg">
											<script type="text/javascript">
                                            var filename ="express/sf_cold_chain/food_ease/cold_chain_home_delivery/";
                                            var id ="express/sf_cold_chain/food_ease/cold_chain_home_delivery/pro";
											if(document.getElementById(id)!=null){
                                            document.getElementById(id).setAttribute("href",filename.replace("/en/","/sc/"));
											}
                                            </script>
										</div>
									
										<div class="item">
											<img src="/images/sfexpress/prix01.jpg">
											<script type="text/javascript">
                                            var filename ="https://www.sfbuy.com/recruit";
                                            var id ="https://www.sfbuy.com/recruitpro";
											if(document.getElementById(id)!=null){
                                            document.getElementById(id).setAttribute("href",filename.replace("/en/","/sc/"));
											}
                                            </script>
										</div>
											
										<div class="item">
											<img src="/images/sfexpress/prix02.jpg">
											<script type="text/javascript">
                                            var filename ="express/sf_cold_chain/pharma_ease/cold_chain_main_line_transportation/";
                                            var id ="express/sf_cold_chain/pharma_ease/cold_chain_main_line_transportation/pro";
											if(document.getElementById(id)!=null){
                                            document.getElementById(id).setAttribute("href",filename.replace("/en/","/sc/"));
											}
                                            </script>
										</div>
											
										<div class="item">	
										    <img src="/images/sfexpress/prix03.jpg">
											<script type="text/javascript">
                                            var filename ="news/Magnate-of-logistics-spent-500-million-on-setting-up-the-hivebox-Where-there-is-people-there-is-hivebox-00001/";
                                            var id ="news/Magnate-of-logistics-spent-500-million-on-setting-up-the-hivebox-Where-there-is-people-there-is-hivebox-00001/pro";
											if(document.getElementById(id)!=null){
                                            document.getElementById(id).setAttribute("href",filename.replace("/en/","/sc/"));
											}
                                            </script>
										</div>
									
							</div>
							<ol class="carousel-indicators">
								<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
								<li data-target="#carousel-example-generic" data-slide-to="1" class=""></li>
								<li data-target="#carousel-example-generic" data-slide-to="2" class=""></li>
								<li data-target="#carousel-example-generic" data-slide-to="3" class=""></li>
							</ol>
						</div>
					</div>
				</div>
			
		</div>
	</div>
</div>



<?php 
 //   $title = 'Test User';
 //   $this->headtitle($title, null);

?>
 
 <?php
 /*   commmendaire  test
<div class="header">
<h1>Welcome to front page</h1>
<table class="table">
    <tr>
        <th>nom</th>
        <th>prenom</th>
        <th>telephone</th>
    </tr>
  
    <?php foreach ($users as $user) :?>
    <tr>
        <td><?php echo $this->escapehtml($user->nom);?></td>
        <td><?php echo $this->escapehtml($user->prenom);?></td>
        <td><?php echo $this->escapehtml($user->telephone);?></td>
    </tr>
    <?php endforeach;?>
</table>
</div>
*/
?>